# Generated by Django 3.1.7 on 2021-03-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('pronouns', models.CharField(choices=[('she/her/hers', 'she/her/hers'), ('he/him/his', 'he/him/his'), ('they/them/theirs', 'they/them/theirs')], max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('comments', models.CharField(blank=True, max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
