# Generated by Django 3.1.7 on 2021-03-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210321_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionregister',
            old_name='comments',
            new_name='comment',
        ),
    ]
