# Generated by Django 3.1.7 on 2021-04-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_status',
            field=models.BooleanField(default=False),
        ),
    ]
