# Generated by Django 3.1.7 on 2021-04-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_session_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionregister',
            name='name',
        ),
        migrations.AddField(
            model_name='sessionregister',
            name='first_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sessionregister',
            name='last_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
