# Generated by Django 3.1.7 on 2021-04-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210406_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='core.sessionregister'),
        ),
    ]
