# Generated by Django 3.1.7 on 2021-04-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210407_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionregister',
            name='sessionId',
        ),
        migrations.AddField(
            model_name='sessionregister',
            name='session_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='core.session'),
        ),
    ]
