# Generated by Django 3.1.7 on 2021-04-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210407_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionregister',
            old_name='session_registrant',
            new_name='registered_session',
        ),
    ]
