# Generated by Django 3.1.7 on 2021-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210408_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionregister',
            name='registered_session',
        ),
        migrations.AddField(
            model_name='sessionregister',
            name='registered_session',
            field=models.ManyToManyField(blank=True, null=True, related_name='registrants', to='core.Session'),
        ),
    ]
