# Generated by Django 3.1.7 on 2021-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210408_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='registrant',
        ),
        migrations.AddField(
            model_name='session',
            name='registrant',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='core.SessionRegister'),
        ),
        migrations.AlterField(
            model_name='sessionregister',
            name='registered_session',
            field=models.ManyToManyField(blank=True, related_name='registrants', to='core.Session'),
        ),
    ]
