# Generated by Django 3.1.7 on 2021-04-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210408_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionregister',
            name='registered_session',
        ),
    ]
