# Generated by Django 3.1.7 on 2021-04-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sessionregister_registered_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='registrant',
        ),
        migrations.AddField(
            model_name='session',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.sessionregister'),
        ),
    ]
