# Generated by Django 3.1.7 on 2021-04-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210408_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='registrant',
        ),
    ]
