# Generated by Django 3.1.7 on 2021-04-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_session_registrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionregister',
            old_name='registered_session',
            new_name='session',
        ),
    ]
