# Generated by Django 3.1.7 on 2021-04-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210408_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionregister',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_registers', to='core.session'),
        ),
    ]
