# Generated by Django 3.1.7 on 2021-04-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210409_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRegistrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('pronouns', models.CharField(choices=[('she/her/hers', 'she/her/hers'), ('he/him/his', 'he/him/his'), ('they/them/theirs', 'they/them/theirs')], max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('comment', models.CharField(blank=True, max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_registrants', to='core.session')),
            ],
        ),
        migrations.DeleteModel(
            name='SessionRegister',
        ),
    ]
