# Generated by Django 3.2 on 2021-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210501_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sessionregistrant',
            name='pronouns',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
