# Generated by Django 3.2 on 2021-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210504_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='number_of_registrants',
            field=models.IntegerField(default=8),
        ),
    ]
