# Generated by Django 3.2 on 2021-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_session_number_of_registrants'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionregistrant',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
