# Generated by Django 3.2 on 2021-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sessionregistrant_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='facilitator',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
