# Generated by Django 3.2 on 2021-05-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_session_facilitator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='number_of_registrants',
            new_name='number_of_registrants_allowed',
        ),
    ]
