# Generated by Django 3.2 on 2021-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_number_of_registrants_session_number_of_registrants_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='facilitator_email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
