# Generated by Django 3.2 on 2021-07-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_session_facilitator_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_to_disappear', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
