# Generated by Django 3.2 on 2021-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionregistrant',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
