# Generated by Django 3.2 on 2021-07-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_sessionregistrant_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionregistrant',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
