# Generated by Django 3.2 on 2021-07-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210706_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionregistrant',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_registrants', to='core.session', verbose_name='session'),
        ),
    ]
